### ISSUE TITLE
Peerconnection error: Failed to create peer connection

### ISSUE THREAD

**Issue by athasamid** [nhancv/nc-android-webrtcpeer#2]
Hi, I face some error when try to make video call

> E/PCRTCClient: Peerconnection error: Failed to create peer connection: Attempt to invoke virtual method 'boolean org.webrtc.PeerConnection.addStream(org.webrtc.MediaStream)' on a null object reference

can anyone help solve this? Thanks

**Comment by JafferSadiqSM** [comment]
Hello athasamid,
Did you fix this issue? I'm also getting the same problem.

**Comment by athasamid** [comment]
I'm just miss configure in coturn server

**Comment by CharalamposTheodorou** [comment]
Same issue here, can you please explain in detail what was the problem?
